### ISSUE TITLE
no hvm association

### ISSUE THREAD

**Issue by functor-flow** [MemechiKekamoto/quantumfusion-node#1]
![image](https://github.com/MemechiKekamoto/quantumfusion-node/assets/115138297/7ab51ec4-ae8b-4f49-b5f5-7250309c3b3f)

**Comment by MemechiKekamoto** [comment]
Yes it does not import HVM yet, please read a roadmap before you start posting accusations.
![Screenshot from 2024-06-25 10-19-06](https://github.com/MemechiKekamoto/quantumfusion-node/assets/172104031/3df66bcd-904c-4700-a942-2fc25640a5d7)
HVM integration works starts next week.

Please do your own research.
